Vagrant.configure(2) do | config |
    config.vm.box = "ubuntu/jammy64"
    config.vm.network "private_network", ip: "192.168.10.1", virtualbox_intent: "networkname"
    # Here in addition to the static ip we defined an network of our own, so that the machines that are connected to the same network only can communicate with each other.
end