# Syntax
# config.vm.synced_folder = "sourceDirectory", "guestMountLocation"

Vagrant.configure(2) do | config |
    config.vm.box = "ubuntu/jammy64"
    config.vm.synced_folder = "D:\workspace\ai-image-generator", "/ai-image-generator"
end